name: Pruebas

on:
    workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '22.5.1' # 22.5.1 is a temporary fix since 22 now points to 22.5.0 that has a bug that breaks installation
      #     registry-url: 'https://registry.npmjs.org'

      - run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: |
          echo '${{ fromJson(env.PACKAGE_JSON).version }}'
          echo '${{ fromJson(env.PACKAGE_JSON).private }}'
          echo '${{ fromJson(env.PACKAGE_JSON).nodeBrowserSkel.badges.coveralls }}'

      - if: ${{ fromJson(env.PACKAGE_JSON).private }} != true && ${{ fromJson(env.PACKAGE_JSON).private }} != 'true'
        run: |
          echo "Publish!"

